<meta charset=utf-8>
<title>Web NFC: Test exceptions in nfc.push</title>
<link rel="author" title="Intel" href="http://www.intel.com"/>
<link rel="author" title="Zhao Ming" href="mailto:mingx.zhao@intel.com"/>
<link rel="help" href="https://w3c.github.io/web-nfc/#the-nfc-interface"/>
<script src="../resources/testharness.js"></script>
<script src="../resources/testharnessreport.js"></script>
<script src="nfc_help.js"></script>

<div id="log"></div>

<script>
"use strict";

//promise_test(t => {
//  return promise_rejects(t, new TypeError(), navigator.nfc.push({data: [{data: null, mediaType: "", recordType: "empty"}]}))
//}, "Test that nfc.push fails with 'TypeError' when message is NFCMessage and recordType is 'empty'.");

//promise_test(t => {
//  let promise = navigator.nfc.push(test_text_data);
//  navigator.nfc.cancelPush();
//  return promise_rejects(t, 'AbortError', promise);
//}, "nfc.cancelPush should reject pending promise with AbortError.");

  return promise_rejects(t, "TimeoutError", navigator.nfc.push(test_text_data, { timeout: 1 }));
}, "nfc.push should fail with TimeoutError when timer expires.");

//promise_test(t => {
//  return promise_rejects(t, new TypeError(), navigator.nfc.push(test_number_data));
//}, "nfc.push should fail with TypeError when parameter is 'number'.");


</script>
